-- Clara Confirms Backend - Initial Schema
-- Creates companies and users tables for multi-tenancy
-- Uses BIGINT (Int8) for IDs instead of UUID

-- ============================================================================
-- Companies (Tenants)
-- ============================================================================

CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  retell_agent_id TEXT,
  retell_phone_number TEXT,
  phone_number TEXT,
  retell_llm_id VARCHAR(255),
  email VARCHAR(255),
  metadata JSONB DEFAULT '{}'::jsonb,
  default_timezone VARCHAR(50) DEFAULT 'America/New_York'
);

-- ============================================================================
-- Users
-- ============================================================================

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL DEFAULT 'user',
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_company_id ON users(company_id);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_company_role ON users(company_id, role, active);
