-- ServiceTrade integration: per-company credentials/session metadata
-- One row per company; password is not stored.

CREATE TABLE servicetrade_integration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  username VARCHAR(255) NOT NULL,
  auth_code TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(company_id)
);

CREATE INDEX idx_servicetrade_integration_company_id ON servicetrade_integration(company_id);
CREATE INDEX idx_servicetrade_integration_is_active ON servicetrade_integration(is_active);
CREATE INDEX idx_servicetrade_integration_is_deleted ON servicetrade_integration(is_deleted);
