-- ServiceTrade integration: per-company credentials
-- One row per company; credentials are stored in a separate table (not in companies)

CREATE TABLE company_servicetrade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  username VARCHAR(255) NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(company_id)
);

CREATE INDEX idx_company_servicetrade_company_id ON company_servicetrade(company_id);
