-- Add is_active and is_deleted to all tables; add metadata to company_servicetrade; create company_settings
-- Convention: is_active BOOLEAN DEFAULT TRUE, is_deleted BOOLEAN DEFAULT FALSE

-- ============================================================================
-- Companies: is_active, is_deleted
-- ============================================================================

ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_companies_is_active ON companies(is_active);
CREATE INDEX IF NOT EXISTS idx_companies_is_deleted ON companies(is_deleted);

-- ============================================================================
-- Users: is_active, is_deleted (keep existing "active" for backward compat)
-- ============================================================================

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

-- Sync is_active from existing active column for existing rows
UPDATE users SET is_active = active WHERE active IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);
CREATE INDEX IF NOT EXISTS idx_users_is_deleted ON users(is_deleted);

-- ============================================================================
-- Company ServiceTrade: is_active, is_deleted, metadata
-- ============================================================================

ALTER TABLE company_servicetrade ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE company_servicetrade ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE company_servicetrade ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_company_servicetrade_is_active ON company_servicetrade(is_active);
CREATE INDEX IF NOT EXISTS idx_company_servicetrade_is_deleted ON company_servicetrade(is_deleted);

-- ============================================================================
-- Company settings: max users and future config (one row per company)
-- ============================================================================

CREATE TABLE company_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  max_users INTEGER NOT NULL DEFAULT 3,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(company_id)
);

CREATE INDEX idx_company_settings_company_id ON company_settings(company_id);
CREATE INDEX idx_company_settings_is_active ON company_settings(is_active);
CREATE INDEX idx_company_settings_is_deleted ON company_settings(is_deleted);
