-- ServiceTrade sync: companies (ST customers), locations, service_requests, contacts, assets, sync_state
-- All synced tables: (servicetrade_id, company_id) unique for idempotent upserts; company_id = Clara tenant (companies.id)
-- Each entity table has payload JSONB for raw API response

-- ST companies (customers in ServiceTrade); phone_number and address from API company.phoneNumber, company.address
CREATE TABLE servicetrade_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  servicetrade_id BIGINT NOT NULL,
  name TEXT,
  phone_number TEXT,
  address TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(servicetrade_id, company_id)
);
CREATE INDEX idx_st_companies_company_id ON servicetrade_companies(company_id);
CREATE INDEX idx_st_companies_active ON servicetrade_companies(company_id, is_active) WHERE is_deleted = FALSE;

-- ST locations (sites under a company); servicetrade_company_id may be null until
-- the company relationship is resolved from ServiceTrade payloads.
CREATE TABLE servicetrade_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  servicetrade_id BIGINT NOT NULL,
  servicetrade_company_id BIGINT,
  name TEXT,
  phone_number TEXT,
  email TEXT,
  address JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(servicetrade_id, company_id)
);
CREATE INDEX idx_st_locations_company_id ON servicetrade_locations(company_id);
CREATE INDEX idx_st_locations_st_company ON servicetrade_locations(company_id, servicetrade_company_id);
CREATE INDEX idx_st_locations_active ON servicetrade_locations(company_id, is_active) WHERE is_deleted = FALSE;

-- ST service requests (at a location)
CREATE TABLE servicetrade_service_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  servicetrade_id BIGINT NOT NULL,
  location_id BIGINT NOT NULL REFERENCES servicetrade_locations(id) ON DELETE CASCADE,
  job_id BIGINT,
  asset_id BIGINT,
  description TEXT,
  status TEXT,
  window_start TIMESTAMPTZ,
  window_end TIMESTAMPTZ,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(servicetrade_id, company_id)
);
CREATE INDEX idx_st_sr_company_id ON servicetrade_service_requests(company_id);
CREATE INDEX idx_st_sr_location_id ON servicetrade_service_requests(location_id);
CREATE INDEX idx_st_sr_status ON servicetrade_service_requests(company_id, status);

-- ST contacts (linked to company/location from payload)
CREATE TABLE servicetrade_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  servicetrade_id BIGINT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  mobile TEXT,
  email TEXT,
  type TEXT,
  location_id BIGINT REFERENCES servicetrade_locations(id) ON DELETE SET NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(servicetrade_id, company_id)
);
CREATE INDEX idx_st_contacts_company_id ON servicetrade_contacts(company_id);
CREATE INDEX idx_st_contacts_location_id ON servicetrade_contacts(location_id);

-- ST contact relationships (contacts can belong to multiple locations/companies)
CREATE TABLE servicetrade_contact_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES servicetrade_contacts(id) ON DELETE CASCADE,
  location_id BIGINT NOT NULL REFERENCES servicetrade_locations(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(contact_id, location_id)
);
CREATE INDEX idx_st_contact_locations_company_id ON servicetrade_contact_locations(company_id);
CREATE INDEX idx_st_contact_locations_contact_id ON servicetrade_contact_locations(contact_id);
CREATE INDEX idx_st_contact_locations_location_id ON servicetrade_contact_locations(location_id);

CREATE TABLE servicetrade_contact_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES servicetrade_contacts(id) ON DELETE CASCADE,
  servicetrade_company_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(contact_id, servicetrade_company_id)
);
CREATE INDEX idx_st_contact_companies_company_id ON servicetrade_contact_companies(company_id);
CREATE INDEX idx_st_contact_companies_contact_id ON servicetrade_contact_companies(contact_id);
CREATE INDEX idx_st_contact_companies_st_company_id ON servicetrade_contact_companies(company_id, servicetrade_company_id);

-- ST assets (linked to location and optionally to SR)
CREATE TABLE servicetrade_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  servicetrade_id BIGINT NOT NULL,
  location_id BIGINT NOT NULL REFERENCES servicetrade_locations(id) ON DELETE CASCADE,
  service_request_id BIGINT REFERENCES servicetrade_service_requests(id) ON DELETE SET NULL,
  name TEXT,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(servicetrade_id, company_id)
);
CREATE INDEX idx_st_assets_company_id ON servicetrade_assets(company_id);
CREATE INDEX idx_st_assets_location_id ON servicetrade_assets(location_id);
CREATE INDEX idx_st_assets_sr_id ON servicetrade_assets(service_request_id);

-- Sync state: one row per Clara company; last_sync_at in Unix seconds
CREATE TABLE servicetrade_sync_state (
  company_id BIGINT NOT NULL PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,
  last_sync_at BIGINT NOT NULL DEFAULT 0
);
