-- Human-written, per-company descriptions of what a technician visit for a
-- given service line actually involves (e.g. "Annual Fire Alarm
-- (Apartments/Hotels): We will need to sound off the entire system..."),
-- injected as reference context into both the voice agent (call_type_configs'
-- general_prompt) and the chat agent (src/confirmation-agent/graph/prompt.js)
-- so either can accurately describe a visit. Matching which description
-- applies to a given appointment is left to the agent's own judgment from
-- the appointment's real service line/job text — there's no property-type
-- or frequency field anywhere in this schema (or in ServiceTrade's data) to
-- match on precisely, and building one wasn't wanted.
CREATE TABLE service_line_descriptions (
  id BIGSERIAL PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, title)
);

INSERT INTO service_line_descriptions (company_id, title, description) VALUES
(9, 'Annual Fire Alarm (Apartments/Hotels)', $desc$We will need to sound off the entire system and get into all areas, including units, to make sure all system devices are working as they should. Per code, we are required to visually look at all system devices during this inspection.$desc$),
(9, 'Annual Fire Sprinkler (Apartments/Hotels)', $desc$We will need to sound off the system briefly and get into all areas, including units, to verify that that the fire sprinkler heads are compliant. Per code, we are required to visually look at all fire sprinkler heads during this inspection to make sure that they aren't loaded with dust and debris, leaking, bent, etc.$desc$),
(9, 'Annual Fire Alarm and Fire Sprinkler (Apartments/Hotels)', $desc$We will need to sound off the entire system and get into all areas, including units, to make sure all system devices are working as they should and verify that that the fire sprinkler heads are compliant. Per code, we are required to visually look at all system devices during this inspection and verify that the sprinkler heads aren't loaded with dust and debris, leaking, bent, etc.$desc$),
(9, 'Annual Fire Alarm (multi-buildings)', $desc$We will need to sound off the system in each building and walk units to make sure all system devices are working as they should. Per code, we are required to visually look at all system devices during this inspection.$desc$),
(9, 'Annual Fire Sprinkler (multi-buildings)', $desc$We will need to sound off the system briefly in each building and get into all areas, including units, to verify that that the fire sprinkler heads are compliant. Per code, we are required to visually look at all fire sprinkler heads during this inspection to make sure that they aren't loaded with dust and debris, leaking, bent, etc.$desc$),
(9, 'Annual Fire Alarm and Fire Sprinkler (multi-buildings)', $desc$We will need to sound off the system in each building and walk units to make sure all system are working as they should and making sure that all fire sprinkler heads are complaint. Per code, we are required to visually look at all system devices during this inspection to ensure that they are operating properly and make sure that the sprinkler heads aren't loaded with dust and debris, leaking, bent, etc.$desc$),
(9, 'Semi-Annual Fire Alarm (Apartments/Hotels)', $desc$We can typically keep the system quiet during this inspection and should be in and out within an hour so. We will need to load test batteries and do a visual inspection. Please expect that the panel will beep locally while load testing the batteries and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Semi-Annual Fire Alarm (multi-buildings)', $desc$We can typically keep the system quiet during this inspection and should be in and out within an hour so. We will need to load test batteries and do a visual inspection for each building. Please expect that the panel will beep locally while load testing the batteries and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Semi-Annual Fire Sprinkler (Apartments/Hotels)', $desc$We will be testing sprinkler components only during this inspection so we will not need to get into units. Please expect that the panel map beep locally during this inspection and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Semi-Annual Fire Sprinkler (multi-buildings)', $desc$We will be testing sprinkler components only during this inspection for each building so we will not need to get into units. Please expect that the panel map beep locally during this inspection and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Quarterly Fire Sprinkler (Apartments/Hotels)', $desc$We will be testing sprinkler components only during this inspection so we will not need to get into units. Please expect that the panel map beep locally during this inspection and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Quarterly Fire Sprinkler (multi-buildings)', $desc$We will be testing sprinkler components only during this inspection for each building so we will not need to get into units. Please expect that the panel map beep locally during this inspection and note that even though we are expecting that the system will not go off, there is always a possibility that it could happen.$desc$),
(9, 'Annual Backflow (on the same job as a sprinkler inspection)', $desc$Clara can just say that the annual fire alarm, fire sprinkler and backflow inspections are due and scheduled for August 6th at 8am. During these inspections we will need to sound the entire system and get into all areas, including units. Per code, we are required to visually look at all system devices during this inspection to ensure that they are operating properly and make sure that the sprinkler heads aren't loaded with dust and debris, leaking, bent, etc.$desc$),
(9, 'Annual Backflow (on a job without any other services)', $desc$We will need to swing by to test the backflow. This could cause the panel to beep locally but we should been in and out fairly quickly.$desc$),
(9, 'Fire Extinguishers (on the same job as a fire alarm inspection)', $desc$Clara can just say that the annual fire alarm, fire sprinkler, backflow and fire extinguisher inspections are due and scheduled for August 6th at 8am. During these inspections we will need to sound the entire system and get into all areas, including units and we will inspect your extinguishers while onsite. Per code, we are required to visually look at all system devices during this inspection to ensure that they are operating properly and make sure that the sprinkler heads aren't loaded with dust and debris, leaking, bent, etc. Note: the fire sprinkler techs do not tag extinguishers — we use either our extinguisher tech or a fire alarm tech if one isn't available.$desc$),
(9, 'Fire Extinguishers (on a job without any other services)', $desc$We will be inspecting and tagging your extinguishers. We will not need to make any noise, but we will need into all areas that have fire extinguishers installed.$desc$);
