-- InspectPoint credentials — the second real CRM integration.
--
-- InspectPoint auth is a static per-tenant API key against a subdomain
-- (https://{subdomain}.inspectpoint.com) — no login handshake, so there is no
-- `username`/session-cookie equivalent the way ServiceTrade has.
--
-- Column names deliberately mirror servicetrade_integration (005_company_servicetrade.sql)
-- even where the semantics differ (`auth_code` holds the API key, not an OAuth
-- code) because two call sites already depend on this exact shape working for
-- ANY `<slug>_integration` table without modification:
--   - routes/admin.js's cron company-discovery query
--   - services/crm/index.js's resolveSlugForCompany()
-- Both do `SELECT ... WHERE is_active = true AND auth_code IS NOT NULL AND auth_code <> ''`.
-- Naming the API-key column anything else would require touching both.

CREATE TABLE inspectpoint_integration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  subdomain TEXT NOT NULL,
  auth_code TEXT,           -- the API key
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(company_id)
);

CREATE INDEX idx_inspectpoint_integration_company_id ON inspectpoint_integration(company_id);
CREATE INDEX idx_inspectpoint_integration_is_active ON inspectpoint_integration(is_active);
CREATE INDEX idx_inspectpoint_integration_is_deleted ON inspectpoint_integration(is_deleted);
