-- ZenTrades credentials — the third real CRM integration.
--
-- ZenTrades auth is session-based: POST /api/auth/login with
-- {username, password, rememberMe: true} returns a 24-hour JWT in the
-- response BODY (result["access-token"]) — no Set-Cookie, no refresh token.
-- This is neither existing pattern: not InspectPoint's static per-tenant API
-- key (nothing to refresh), and not ServiceTrade's either despite looking
-- similar — ServiceTrade logs in with one GLOBAL service account from env
-- and stores only the resulting session cookie, so it never stores a
-- password. ZenTrades' JWT carries companyId in its own claims, so
-- credentials are inherently per-tenant: there is no global account to fall
-- back on, which means the password itself must be the durable secret we
-- keep, so we can log back in unattended when the 24h token expires.
--
-- `auth_code` therefore holds the password, AES-256-GCM-encrypted at rest via
-- src/utils/crypto.js (see CREDENTIAL_ENCRYPTION_KEY). Column names otherwise
-- mirror servicetrade_integration / inspectpoint_integration on purpose —
-- two call sites already depend on ANY `<slug>_integration` table having
-- this exact shape without modification:
--   - routes/admin.js's cron company-discovery query
--   - services/crm/index.js's resolveSlugForCompany()
-- Both do `SELECT ... WHERE is_active = true AND auth_code IS NOT NULL AND auth_code <> ''`.
-- Naming the encrypted-password column anything else would require touching both.
--
-- access_token / access_token_expires_at cache the current JWT so most runs
-- don't need a fresh login at all — expires_at is read from the token's own
-- `exp` claim, never computed from a guessed TTL.
--
-- auth_status / auth_failed_at / auth_error track what happens when the
-- password stops working (rotated upstream, or the account's rememberMe
-- window lapses): login starts returning 403. That must become a visible,
-- actionable state rather than a recurring sync error nobody reads — see
-- services/zentrades.js's login(). Deliberately NOT expressed by clearing
-- auth_code: resolveSlugForCompany() falls back to "servicetrade" the moment
-- auth_code is empty, so clearing it on a bad password would silently
-- reclassify the company as a ServiceTrade tenant mid-conversation. The row
-- must stay discoverable; only auth_status changes.

CREATE TABLE zentrades_integration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  auth_code TEXT,                          -- the encrypted password (see header)
  access_token TEXT,                       -- cached 24h JWT
  access_token_expires_at TIMESTAMPTZ,      -- from the JWT's own `exp` claim
  auth_status TEXT NOT NULL DEFAULT 'ok',   -- 'ok' | 'invalid_credentials' | 'forbidden'
  auth_failed_at TIMESTAMPTZ,
  auth_error TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,       -- {zentradesCompanyId, zentradesUserId, timezoneRegionName}
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(company_id),
  CHECK (auth_status IN ('ok', 'invalid_credentials', 'forbidden'))
);

CREATE INDEX idx_zentrades_integration_company_id ON zentrades_integration(company_id);
CREATE INDEX idx_zentrades_integration_is_active ON zentrades_integration(is_active);
CREATE INDEX idx_zentrades_integration_is_deleted ON zentrades_integration(is_deleted);
