-- CSV / Excel import — for companies with no CRM at all.
--
-- Three tables, mirroring the two-layer architecture every other integration
-- here uses (raw mirror -> normalize -> platform tables):
--
--   csv_integration   marks a company as "CSV mode" so resolveSlugForCompany
--                     stops defaulting it to ServiceTrade
--   csv_imports       one row per uploaded FILE — who uploaded it, when, what
--                     happened, and the file itself for 30 days
--   csv_import_rows   the RAW layer — one row per spreadsheet row, exactly as
--                     it was read, before any interpretation
--
-- Numbered 109 rather than 107/108 deliberately: those two are already taken
-- by the ZenTrades work on its own branch, and scripts/run-migrations.js keeps
-- no applied-migrations ledger — it just sorts by filename — so a colliding
-- number would silently re-run or skip on merge.

-- ── csv_integration ─────────────────────────────────────────────────────────
--
-- Column names mirror inspectpoint_integration (103) / servicetrade_integration
-- (005) even though CSV has no credentials to hold, because two call sites
-- discover integrations by probing ANY `<slug>_integration` table with the same
-- query — `WHERE is_active = true AND auth_code IS NOT NULL AND auth_code <> ''`:
--   - services/crm/index.js's resolveSlugForCompany()
--   - routes/admin.js's crm-sync cron company-discovery
--
-- That predicate is why `auth_code` carries the sentinel 'csv' rather than NULL:
-- a NULL would make the company invisible to resolveSlugForCompany and it would
-- fall back to 'servicetrade'. The sentinel is load-bearing, not decorative.
--
-- Because the SAME predicate also makes the 2-hourly cron call
-- provider.syncAll(companyId), CsvProvider overrides syncAll as a no-op — the
-- base class throws. See src/services/crm/csv/provider.js.

CREATE TABLE csv_integration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  -- Always the literal 'csv'. Present only to satisfy the discovery predicate
  -- above; there is nothing to authenticate against.
  auth_code TEXT NOT NULL DEFAULT 'csv',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(company_id)
);

CREATE INDEX idx_csv_integration_company_id ON csv_integration(company_id);
CREATE INDEX idx_csv_integration_is_active ON csv_integration(is_active);

-- ── csv_imports — one row per uploaded file ─────────────────────────────────
--
-- This is the archive the office sees: who uploaded what, when, and how it
-- went. The record is kept indefinitely; only the FILE ITSELF expires.
--
-- `raw_content` holds the uploaded file's own text so an import can be re-run
-- without asking anyone to find the file again. It is this deployment's
-- stand-in for the object store the reference implementation used — uploads are
-- capped at 4 MB at the route (the platform's request-body ceiling), so these
-- rows stay comfortably TOAST-able.
--
-- RETENTION: `raw_content` and the rows in csv_import_rows are purged 30 days
-- after upload by /admin/csv-imports/gc, and `content_purged_at` is stamped so
-- the UI can say "the file is no longer available" rather than offering a
-- re-run that would fail. The summary row survives the purge, so the archive
-- list stays complete forever.
--
-- NOT encrypted at rest beyond whatever the database itself provides. A
-- customer list is ordinary business data of the same sensitivity as the
-- `customers` table it becomes, and this codebase has no field-encryption
-- utility to reuse. Access is company-scoped on every read (see
-- db/csv-imports.js, where companyId is a required argument rather than an
-- optional filter).

CREATE TABLE csv_imports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  -- Who uploaded it. ON DELETE SET NULL so removing a user doesn't erase the
  -- audit trail of what was imported.
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  -- Denormalised at upload time so the archive still shows a name after the
  -- user is deactivated or their row is gone.
  uploaded_by_email TEXT,

  filename TEXT NOT NULL,
  file_size INTEGER,
  -- NULLable because the 30-day purge clears it while keeping the record.
  raw_content TEXT,
  content_purged_at TIMESTAMPTZ,

  -- pending  — stored, not yet processed (also the dry-run/preview state)
  -- running  — an engine run is working through it
  -- completed| failed — terminal
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  engine_run_id BIGINT,

  -- How D/M/Y slash dates in this file were read. Recorded because it is a
  -- per-file decision (see services/csv-import/mapper.js) and a support
  -- question later — "why is this visit in April?" — is unanswerable without it.
  date_order TEXT CHECK (date_order IN ('DMY', 'MDY', 'ISO_ONLY')),

  -- The column mapping this import actually used, {field: "Their Header"}.
  -- Stored per-import rather than only as the company default because the
  -- default can change: "why did the March file put the phone in the wrong
  -- place" is only answerable against the mapping that run used.
  column_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,

  total_rows INTEGER NOT NULL DEFAULT 0,
  imported_rows INTEGER NOT NULL DEFAULT 0,
  error_rows INTEGER NOT NULL DEFAULT 0,
  -- Capped at the application layer (see db/csv-imports.js) — an unbounded
  -- array of every bad row, each carrying the full row, is how a 50k-error
  -- file turns one column into hundreds of MB. The per-row detail lives in
  -- csv_import_rows anyway; this is just the summary the list view reads.
  errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  error TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_csv_imports_company_created ON csv_imports(company_id, created_at DESC);
CREATE INDEX idx_csv_imports_status ON csv_imports(status) WHERE status IN ('pending', 'running');
-- Drives the retention sweep: find un-purged uploads past their expiry.
CREATE INDEX idx_csv_imports_purge ON csv_imports(created_at) WHERE content_purged_at IS NULL;

-- ── csv_import_rows — the RAW layer ─────────────────────────────────────────
--
-- One row per spreadsheet row, stored exactly as parsed: every cell a string,
-- nothing interpreted. Same role as inspectpoint_* / servicetrade_* raw tables
-- (104, 045) — a faithful mirror of what the source actually said, separate
-- from our interpretation of it.
--
-- Why this layer earns its keep for a file upload, where there is no remote
-- API to mirror:
--   - re-normalize without re-parsing, and (once the file is purged) without
--     the file existing at all
--   - per-row provenance: "row 14 failed" can show the original cells next to
--     the reason, which is the difference between a usable error report and
--     "something was wrong with your spreadsheet"
--   - a mapper fix can be replayed against every historical import to see what
--     WOULD have changed, before shipping it
--
-- Promoted columns follow 104's rule — only a soft FK, a filter, or a status
-- becomes a column; everything else lives in `payload`. So `reference` (the
-- upsert key) and `job_reference` (the grouping soft-link) are columns, and
-- the customer name, phone, address and every unrecognised column are not.
--
-- `mapped` is the typed result of interpreting `payload` (UTC instants,
-- E.164 phone, and so on), or NULL when the row could not be read — in which
-- case `error` says why. Keeping both side by side is what makes the raw layer
-- debuggable rather than merely archival.

CREATE TABLE csv_import_rows (
  id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  csv_import_id BIGINT NOT NULL REFERENCES csv_imports(id) ON DELETE CASCADE,

  -- The line number as the user sees it in Excel (header is row 1), so an
  -- error message can quote it directly.
  row_number INTEGER NOT NULL,

  reference TEXT,      -- becomes appointments.external_ref
  job_reference TEXT,  -- soft link -> the job several visits share

  payload JSONB NOT NULL DEFAULT '{}'::jsonb,  -- the raw cells, all strings
  mapped JSONB,                                -- the typed interpretation, or NULL
  error TEXT,                                  -- why this row could not be read

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (csv_import_id, row_number)
);

-- ── csv_column_mappings — the company's remembered mapping ──────────────────
--
-- A company exports the same report every week, so making them redraw the
-- mapping each time would be the single most annoying thing about this
-- feature. The last mapping they confirmed is saved here and applied
-- automatically to their next upload; the upload can always override it, and
-- doing so updates the saved one.
--
-- One row per company (not per file shape). A company with two genuinely
-- different exports is a real case but not today's — when it turns up, add a
-- header fingerprint column and relax the unique constraint, rather than
-- guessing at that shape now.

CREATE TABLE csv_column_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- The headers this mapping was drawn against, so the UI can warn when a new
  -- file's columns have changed enough that the saved mapping may not fit.
  source_headers JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id)
);

CREATE INDEX idx_csv_import_rows_import ON csv_import_rows(csv_import_id, row_number);
CREATE INDEX idx_csv_import_rows_company ON csv_import_rows(company_id);
-- The error report reads only the failed rows.
CREATE INDEX idx_csv_import_rows_errors ON csv_import_rows(csv_import_id) WHERE error IS NOT NULL;
