-- CSV import — remembered column mappings.
--
-- ── Why this is a separate migration from 109 ───────────────────────────────
--
-- 109 was applied to at least one environment BEFORE the column-mapping
-- feature existed, so the two things it now also declares — `csv_imports
-- .column_mapping` and the `csv_column_mappings` table — are missing there
-- even though the file contains them. scripts/run-migrations.js keeps no
-- applied-migrations ledger (it just sorts filenames), so re-running 109 is not
-- an option: it would fail on the tables it already created.
--
-- Hence a forward-only delta. Everything below is IF NOT EXISTS / ADD COLUMN
-- IF NOT EXISTS, so this is safe to run against either state:
--   - an environment that got the OLD 109 → this adds the two missing pieces
--   - a fresh environment that runs the CURRENT 109 → this no-ops
-- Do not "tidy up" by removing the declarations from 109; a fresh database
-- must still be correct if only 109 is applied.

-- The mapping an individual import actually used. Per-import as well as per
-- company, because the company default can change — "why did the March file
-- put the phone in the wrong place" is only answerable against the mapping
-- that run used, not against whatever is current now.
ALTER TABLE csv_imports
  ADD COLUMN IF NOT EXISTS column_mapping JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ── csv_column_mappings — the company's remembered mapping ──────────────────
--
-- A company exports the same report every week, so making them redraw the
-- mapping each time would be the single most annoying thing about this
-- feature. The last mapping they explicitly confirmed is saved here and
-- applied automatically to their next upload; an upload can always override
-- it, and doing so updates the saved one.
--
-- Only ever written from a mapping the USER supplied — never from our own
-- suggestions, which would let a guess inherit the authority of an approval.
--
-- One row per company, not per file shape. A company with two genuinely
-- different exports is a real case but not today's; when it turns up, add a
-- header fingerprint column and relax the unique constraint, rather than
-- guessing at that shape now.

CREATE TABLE IF NOT EXISTS csv_column_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- The headers this mapping was drawn against, so the UI can warn when a new
  -- file's columns have drifted far enough that the saved mapping may not fit.
  source_headers JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id)
);

CREATE INDEX IF NOT EXISTS idx_csv_column_mappings_company ON csv_column_mappings(company_id);
